project:
    project_name: App Data Categorization
    description: Categorize app data
    version: 0.0

input_data:
    data_location: mock
    local_directory: mockdata/mockdata
    data_format: csv

configurations:
    df_type: 'pandas'

features:
    - location: 'https://github.com/RADAR-base-Analytics/appdatacategorization'
      feature_groups:
        - AppCategorizationFeatures
      feature_names:
        - all

output_data:
    output_location: local
    local_directory: output/categorized_app
    data_format: csv
    compress: false
